/**
 * Just enough XML to read a showplan.
 *
 * A dependency was the obvious alternative and is the wrong one here: the
 * extension ships two, both database drivers, and adding a third to read one
 * document shape would be a parser, its transitive tree and its release
 * cadence in exchange for eighty lines. Showplan is machine-generated by SQL
 * Server, so it has no doctype, no entities beyond the five predefined ones,
 * no processing instructions worth keeping and no mixed content — which is
 * exactly the subset a scanner can read correctly.
 */
export interface XmlElement {
  name: string;
  attributes: Record<string, string>;
  children: XmlElement[];
}

const ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'"
};

function decode(text: string): string {
  return text.replace(/&(#x?[0-9a-fA-F]+|[a-z]+);/g, (whole, body: string) => {
    if (body.startsWith('#x') || body.startsWith('#X')) {
      return String.fromCodePoint(parseInt(body.slice(2), 16));
    }
    if (body.startsWith('#')) {
      return String.fromCodePoint(parseInt(body.slice(1), 10));
    }
    return ENTITIES[body] ?? whole;
  });
}

export function parseXml(source: string): XmlElement | null {
  const root: XmlElement = { name: '#document', attributes: {}, children: [] };
  const stack: XmlElement[] = [root];
  let i = 0;

  while (i < source.length) {
    const open = source.indexOf('<', i);
    if (open === -1) {
      break;
    }
    i = open + 1;

    if (source.startsWith('!--', i)) {
      const end = source.indexOf('-->', i);
      i = end === -1 ? source.length : end + 3;
      continue;
    }
    if (source.startsWith('![CDATA[', i)) {
      const end = source.indexOf(']]>', i);
      i = end === -1 ? source.length : end + 3;
      continue;
    }
    if (source[i] === '?' || source[i] === '!') {
      const end = source.indexOf('>', i);
      i = end === -1 ? source.length : end + 1;
      continue;
    }
    if (source[i] === '/') {
      const end = source.indexOf('>', i);
      if (stack.length > 1) {
        stack.pop();
      }
      i = end === -1 ? source.length : end + 1;
      continue;
    }

    const end = findTagEnd(source, i);
    if (end === -1) {
      break;
    }
    const body = source.slice(i, end);
    const selfClosing = body.endsWith('/');
    const inner = selfClosing ? body.slice(0, -1) : body;

    const nameMatch = /^[^\s/>]+/.exec(inner);
    if (!nameMatch) {
      i = end + 1;
      continue;
    }
    const element: XmlElement = {
      // Namespace prefixes are dropped: showplan declares one on the root and
      // nothing in the document distinguishes elements by it.
      name: nameMatch[0].replace(/^.*:/, ''),
      attributes: {},
      children: []
    };

    const attributes = /([^\s=]+)\s*=\s*"([^"]*)"|([^\s=]+)\s*=\s*'([^']*)'/g;
    let attribute = attributes.exec(inner.slice(nameMatch[0].length));
    while (attribute) {
      const key = (attribute[1] ?? attribute[3]).replace(/^.*:/, '');
      element.attributes[key] = decode(attribute[2] ?? attribute[4] ?? '');
      attribute = attributes.exec(inner.slice(nameMatch[0].length));
    }

    stack[stack.length - 1].children.push(element);
    if (!selfClosing) {
      stack.push(element);
    }
    i = end + 1;
  }

  return root.children[0] ?? null;
}

/** The `>` that closes a tag, skipping any inside a quoted attribute value. */
function findTagEnd(source: string, from: number): number {
  let quote: string | null = null;
  for (let i = from; i < source.length; i++) {
    const ch = source[i];
    if (quote) {
      if (ch === quote) {
        quote = null;
      }
      continue;
    }
    if (ch === '"' || ch === "'") {
      quote = ch;
      continue;
    }
    if (ch === '>') {
      return i;
    }
  }
  return -1;
}

export function childrenNamed(element: XmlElement, name: string): XmlElement[] {
  return element.children.filter((child) => child.name === name);
}

export function firstNamed(element: XmlElement, name: string): XmlElement | undefined {
  return element.children.find((child) => child.name === name);
}

/** Every descendant with this name, in document order. */
export function descendants(element: XmlElement, name: string): XmlElement[] {
  const out: XmlElement[] = [];
  const walk = (node: XmlElement) => {
    for (const child of node.children) {
      if (child.name === name) {
        out.push(child);
      }
      walk(child);
    }
  };
  walk(element);
  return out;
}
